insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 1357 - Status changed from Pending to Denied');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 1357 - Status changed from Pending to Denied');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 5793 - Status changed from Denied to Completed');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 1357 - Status changed from Pending to Denied');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 5793 - Status changed from Denied to Completed');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 5793 - Status changed from Denied to Completed');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 5793 - Status changed from Denied to Completed');
insert into status_adocao (nome) values ('Adoption 1357 - Status changed from Pending to Denied');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 5793 - Status changed from Denied to Completed');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 1357 - Status changed from Pending to Denied');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 1357 - Status changed from Pending to Denied');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 1111 - Status changed from Approved to Pending');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 9999 - Status changed from Completed to In Progress');
insert into status_adocao (nome) values ('Adoption 8642 - Status changed from In Progress to Approved');
insert into status_adocao (nome) values ('Adoption 1234 - Status changed from Pending to Approved');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 4321 - Status changed from Approved to In Progress');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 5678 - Status changed from In Progress to Completed');
insert into status_adocao (nome) values ('Adoption 2468 - Status changed from Completed to Denied');
insert into status_adocao (nome) values ('Adoption 9876 - Status changed from Denied to Pending');
