--CRIANDO TABELA FEIRINHA
CREATE TABLE IF NOT EXISTS FEIRINHAS (
    ID_FEIRINHA SERIAL PRIMARY KEY,
    ID_RESPONSAVEL INT NOT NULL REFERENCES USUARIOS(ID_USUARIO) ON DELETE RESTRICT,
    DATA_INICIO_FEIRA DATE NOT NULL,
    DATA_FIM_FEIRA DATE NOT NULL,
    LOCALIZACAO VARCHAR(255) NOT NULL
);

--COMENTARIOS SOBRE AS COLUNAS 
COMMENT ON COLUMN FEIRINHAS.ID_RESPONSAVEL IS 'Usuário responsável pela feirinha (apenas 1)';
COMMENT ON COLUMN FEIRINHAS.DATA_INICIO_FEIRA IS 'Data de início da feirinha (ISO 8601)';
COMMENT ON COLUMN FEIRINHAS.DATA_FIM_FEIRA IS 'Data de finalização da feirinha (ISO 8601)';
COMMENT ON COLUMN FEIRINHAS.LOCALIZACAO IS 'Local onde a feirinha ocorrerá';

-- 2. Tabela de vínculo MUITO PARA MUITOS entre feirinhas e voluntários
CREATE TABLE IF NOT EXISTS FEIRINHAS_VOLUNTARIOS (
    ID_FEIRINHA INT NOT NULL REFERENCES FEIRINHAS(ID_FEIRINHA) ON DELETE CASCADE,
    ID_VOLUNTARIO INT NOT NULL REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    PRIMARY KEY (ID_FEIRINHA, ID_VOLUNTARIO)
);

COMMENT ON TABLE FEIRINHAS_VOLUNTARIOS IS 'Vincula múltiplos voluntários a uma feirinha';

-- 3. Tabela de vínculo MUITO PARA MUITOS entre feirinhas e animais
CREATE TABLE IF NOT EXISTS FEIRINHAS_ANIMAIS (
    ID_FEIRINHA INT NOT NULL REFERENCES FEIRINHAS(ID_FEIRINHA) ON DELETE CASCADE,
    ID_ANIMAL INT NOT NULL REFERENCES ANIMAIS(ID_ANIMAL) ON DELETE CASCADE,
    PRIMARY KEY (ID_FEIRINHA, ID_ANIMAL)
);

COMMENT ON TABLE FEIRINHAS_ANIMAIS IS 'Vincula múltiplos animais a uma feirinha';


-- 4. Índices de apoio
CREATE INDEX IF NOT EXISTS IDX_FEIRINHAS_RESPONSAVEL ON FEIRINHAS(ID_RESPONSAVEL);
CREATE INDEX IF NOT EXISTS IDX_FEIRINHAS_VOLUNTARIOS ON FEIRINHAS_VOLUNTARIOS(ID_VOLUNTARIO);
CREATE INDEX IF NOT EXISTS IDX_FEIRINHAS_ANIMAIS ON FEIRINHAS_ANIMAIS(ID_ANIMAL);








