CREATE TABLE IF NOT EXISTS FEIRINHAS_ANIMAIS (
    ID_FEIRINHA INT NOT NULL REFERENCES FEIRINHAS(ID_FEIRINHA) ON DELETE CASCADE,
    ID_ANIMAL INT NOT NULL REFERENCES ANIMAIS(ID_ANIMAL) ON DELETE CASCADE,
    PRIMARY KEY (ID_FEIRINHA, ID_ANIMAL)
);
