insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Grooming supplies donation for guinea pigs');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Medicine donation for horses');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Training equipment donation for ferrets');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Pet bed donation for hamsters');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Monetary donation for dogs');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Blanket donation for birds');
insert into tipos_doacoes (nome) values ('Treat donation for fish');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
insert into tipos_doacoes (nome) values ('Cleaning supplies donation for turtles');
insert into tipos_doacoes (nome) values ('Food donation for cats');
insert into tipos_doacoes (nome) values ('Toy donation for rabbits');
